# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-06 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claimid', models.CharField(db_column='ClaimID', max_length=20, primary_key=True, serialize=False)),
                ('claimdate', models.DateField(blank=True, db_column='ClaimDate', null=True)),
                ('hospitalstartdate', models.DateField(blank=True, db_column='HospitalStartDate', null=True)),
                ('hospitalenddate', models.DateField(blank=True, db_column='HospitalEndDate', null=True)),
                ('patientcopay', models.IntegerField(blank=True, db_column='PatientCoPay', null=True)),
                ('claimstatus', models.CharField(blank=True, db_column='ClaimStatus', max_length=20, null=True)),
                ('opendate', models.DateField(blank=True, db_column='OpenDate', null=True)),
                ('approvedate', models.DateField(blank=True, db_column='ApproveDate', null=True)),
                ('denydate', models.DateField(blank=True, db_column='DenyDate', null=True)),
                ('rejectdate', models.DateField(blank=True, db_column='RejectDate', null=True)),
                ('repealdate', models.DateField(blank=True, db_column='RepealDate', null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Claim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('conditionid', models.CharField(db_column='ConditionID', max_length=20, primary_key=True, serialize=False)),
                ('innetworkcoverage', models.CharField(blank=True, db_column='InNetworkCoverage', max_length=255, null=True)),
                ('outnetworkcoverage', models.CharField(blank=True, db_column='OutNetworkCoverage', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Conditions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Druginventory',
            fields=[
                ('drugid', models.CharField(db_column='drugId', max_length=20, primary_key=True, serialize=False)),
                ('drugkind', models.CharField(blank=True, db_column='drugKind', max_length=20, null=True)),
                ('drugname', models.CharField(blank=True, db_column='drugName', max_length=20, null=True)),
                ('drugquantity', models.CharField(blank=True, db_column='drugQuantity', max_length=20, null=True)),
                ('inventorylocation', models.CharField(blank=True, db_column='inventoryLocation', max_length=20, null=True)),
            ],
            options={
                'db_table': 'DrugInventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Druginventoryprescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptionid', models.CharField(db_column='prescriptionId', max_length=20)),
                ('fulfilled', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'DrugInventoryPrescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fulfilment',
            fields=[
                ('fulfilmentid', models.CharField(db_column='fulfilmentId', max_length=20, primary_key=True, serialize=False)),
                ('datefilled', models.CharField(blank=True, db_column='dateFilled', max_length=20, null=True)),
                ('receiverfirstname', models.CharField(blank=True, db_column='receiverFirstName', max_length=20, null=True)),
                ('receiverlastname', models.CharField(blank=True, db_column='receiverLastName', max_length=20, null=True)),
                ('generic', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Fulfilment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.CharField(db_column='PatientID', max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=255, null=True)),
                ('patientaddress', models.CharField(blank=True, db_column='PatientAddress', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('patientstate', models.CharField(blank=True, db_column='PatientState', max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, db_column='ZipCode', null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=255, null=True)),
                ('dateofbirth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('employment', models.IntegerField(blank=True, db_column='Employment', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyid', models.CharField(db_column='pharmacyId', max_length=20)),
                ('pharmacistid', models.CharField(db_column='pharmacistId', max_length=20)),
                ('technicianid', models.CharField(db_column='technicianId', max_length=20)),
                ('pharmacyname', models.CharField(blank=True, db_column='pharmacyName', max_length=20, null=True)),
                ('pharmacylocation', models.CharField(blank=True, db_column='pharmacyLocation', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('physicianid', models.CharField(db_column='physicianId', max_length=20, primary_key=True, serialize=False)),
                ('physicianfirstname', models.CharField(blank=True, db_column='physicianFirstName', max_length=20, null=True)),
                ('physicianlastname', models.CharField(blank=True, db_column='physicianLastName', max_length=20, null=True)),
                ('physicianphonenumber', models.CharField(blank=True, db_column='physicianPhoneNumber', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Physician',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyid', models.CharField(db_column='PolicyID', max_length=20, primary_key=True, serialize=False)),
                ('policyname', models.CharField(blank=True, db_column='PolicyName', max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('policytype', models.CharField(blank=True, db_column='PolicyType', max_length=255, null=True)),
                ('patientid', models.CharField(blank=True, db_column='PatientID', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Policy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescriptionid', models.CharField(db_column='prescriptionId', max_length=20)),
                ('dateissued', models.CharField(blank=True, db_column='dateIssued', max_length=20, null=True)),
                ('numberissued', models.CharField(blank=True, db_column='numberIssued', max_length=20, null=True)),
                ('dosagenumber', models.CharField(blank=True, db_column='dosageNumber', max_length=20, null=True)),
                ('dosagefrequency', models.CharField(blank=True, db_column='dosageFrequency', max_length=20, null=True)),
                ('purpose', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Prescription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('providerid', models.CharField(db_column='ProviderID', max_length=20, primary_key=True, serialize=False)),
                ('providername', models.CharField(blank=True, db_column='ProviderName', max_length=255, null=True)),
                ('providertype', models.CharField(blank=True, db_column='ProviderType', max_length=255, null=True)),
                ('networktype', models.CharField(blank=True, db_column='NetworkType', max_length=255, null=True)),
                ('provideraddress', models.CharField(blank=True, db_column='ProviderAddress', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('providerstate', models.CharField(blank=True, db_column='ProviderState', max_length=255, null=True)),
                ('zipcode', models.IntegerField(blank=True, db_column='ZipCode', null=True)),
                ('phonenumber', models.CharField(blank=True, db_column='PhoneNumber', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReasonForDenial',
            fields=[
                ('reasonid', models.CharField(db_column='ReasonID', max_length=20, primary_key=True, serialize=False)),
                ('reasondescription', models.CharField(blank=True, db_column='ReasonDescription', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ReasonForDenial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceReceived',
            fields=[
                ('serviceid', models.CharField(db_column='ServiceID', max_length=20, primary_key=True, serialize=False)),
                ('servicename', models.CharField(blank=True, db_column='ServiceName', max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('enddate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('cost', models.IntegerField(blank=True, db_column='Cost', null=True)),
            ],
            options={
                'db_table': 'ServiceReceived',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('servicetypeid', models.CharField(db_column='ServiceTypeID', max_length=20, primary_key=True, serialize=False)),
                ('typename', models.CharField(blank=True, db_column='TypeName', max_length=255, null=True)),
                ('servicecategory', models.CharField(blank=True, db_column='ServiceCategory', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.CharField(db_column='StaffID', max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=255, null=True)),
                ('staffrole', models.CharField(blank=True, db_column='StaffRole', max_length=255, null=True)),
                ('susername', models.CharField(blank=True, db_column='SUsername', max_length=50, null=True)),
                ('spassword', models.CharField(blank=True, db_column='SPassword', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
    ]
